/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.ejemplopersistencia.views;

import com.mycompany.ejemplopersistencia.persistence.PersistenceMySQl;
import com.mycompany.ejemplopersistencia.services.ShowWindows;
import lombok.Getter;

import javax.swing.*;

/**
 * @author masu
 */
public class MainAppDialog extends javax.swing.JDialog {

    /**
     * Creates new form MainAppDialog
     */
    public MainAppDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsuarioTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BotonDarseDeBaja = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seguimos trabajando en esta aplicacion,");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 720, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("puedes darte de baja aqui:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 480, -1));

        UsuarioTextField.setBackground(new java.awt.Color(255, 255, 255));
        UsuarioTextField.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        getContentPane().add(UsuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 350, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Introduce tu usuario para confirmar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 350, -1));

        BotonDarseDeBaja.setBackground(new java.awt.Color(255, 255, 255));
        BotonDarseDeBaja.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        BotonDarseDeBaja.setForeground(new java.awt.Color(0, 0, 0));
        BotonDarseDeBaja.setText("Darse de baja");
        BotonDarseDeBaja.setBorder(null);
        BotonDarseDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDarseDeBajaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonDarseDeBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, -70, 1850, 2250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDarseDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDarseDeBajaActionPerformed
        if (UsuarioTextField.getText().trim().equals(this.getTitle().substring((this.getTitle().indexOf(":") + 1)).trim())){
            new PersistenceMySQl().delete(UsuarioTextField.getText());
            JOptionPane.showMessageDialog(null, "Usuario eliminado correctamente");
            ShowWindows.initMainFrame();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no coincide con el usuario actual", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonDarseDeBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainAppDialog dialog = new MainAppDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton BotonDarseDeBaja;
    private static javax.swing.JTextField UsuarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
